coub:
  secrets:
    access_token: "token"
  urls:
    base_url: "http://coub.com"

instagram:
  creds_path: /path/auth.json
  creds:
    login: "login"
    password: "password"
  suitability_time: 96
  material_accounts:
    - instagram
  material_count_to_fetch: 5

storage:
  tmp: "/videos/tmp"
  finished: "/videos/finished"
  static: "/videos/static"
  prod: "/videos/prod"

video:
  length: 300000
  timings:
    fetch_material: "0 * * * * *"
    generate_production_video: "0 * * * * *"
    upload_video: "0 * * * * *"
