coub:
  secrets:
    access_token: "token"
  urls:
    base_url: "http://coub.com"

instagram:
  creds_path: /path/auth.json
  creds:
    login: "login"
    password: "password"
  suitability_time: 96

storage:
  tmp: "/videos/tmp"
  finished: "/videos/finished"
  static: "/videos/static"
  prod: "/videos/prod"
